version: '3'                                   
services:                                      
  odoo:                                        
    image: odoo:17.0                           
    env_file: .env                             
    depends_on:                                
      - postgres                               
    ports:                                     
      - "127.0.0.1:8069:8069"                  
    volumes:                                   
      - data:/var/lib/odoo                     
      - config:/etc/odoo                       
    networks:                                  
      - odoo-net                               
  postgres:                                    
    image: postgres:alpine                     
    env_file: .env                             
    volumes:                                   
      - db:/var/lib/postgresql/data/pgdata     
    networks:                                  
      - odoo-net                               
  proxy:                                       
    build: proxy                               
    restart: unless-stopped                    
    ports:                                     
      - 80:80                                  
    depends_on:                                
      - odoo                                   
    networks:                                  
      - odoo-net                               
                                               
networks:                                      
  odoo-net:                                    
                                               
volumes:                                       
  data:                                        
  config:                                      
  db:                                          